services:
  - type: web
    name: bbl-lnb-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: pnpm install && pnpm prisma:generate:prod && pnpm build
    startCommand: pnpm prisma:migrate:deploy && pnpm start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: bbl-lnb-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "15m"
      - key: JWT_REFRESH_EXPIRES_IN
        value: "7d"
      - key: BASKETBALL_API_KEY
        sync: false
      - key: BASKETBALL_API_URL
        value: "https://apiv2.allsportsapi.com/basketball/"
      - key: ADMIN_SECRET_KEY
        generateValue: true
      - key: LEAGUE_API_KEY_BBL
        value: "757"
      - key: LEAGUE_API_KEY_LNB
        value: "756"

databases:
  - name: bbl-lnb-db
    databaseName: basketball_db
    user: postgres
    plan: starter
    region: oregon
